services:
  steps:
    image: ghcr.io/sagehere/zepp-steps:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    ports:
      - "101:8000"
    volumes:
      - ./data:/data
